pipeline:
    # PRODUCTION
    image-private:
        image: plugins/docker
        group: production
        registry: registry.joseluisq.net
        repo: registry.joseluisq.net/rust-linux-darwin-builder
        dockerfile: ./Dockerfile
        username:
            from_secret: registry_username
        password:
            from_secret: registry_password
        auto_tag: true
        build_args:
            - DOCKER_IMAGE_VERSION=${DRONE_TAG}
        when:
            event: tag

    image-public:
        image: plugins/docker
        group: production
        repo: joseluisq/rust-linux-darwin-builder
        dockerfile: ./Dockerfile
        username:
            from_secret: dockerhub_username
        password:
            from_secret: dockerhub_password
        auto_tag: true
        build_args:
            - DOCKER_IMAGE_VERSION=${DRONE_TAG}
        when:
            event: tag

    notification-slack:
        image: plugins/slack
        webhook:
            from_secret: slack_webhook
        channel: ci-cd
        when:
            status: [success, failure]
