---
kind: pipeline
type: docker
name: development

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker build -f ./docker/Dockerfile -t joseluisq/rust-linux-darwin-builder:latest .

- name: test
  image: joseluisq/rust-linux-darwin-builder:latest
  pull: if-not-exists
  commands:
    - make ci-test

trigger:
  event:
    - push
    - pull_request
    - tag

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock


---
kind: pipeline
type: docker
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: joseluisq/rust-linux-darwin-builder
    dockerfile: ./docker/Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    auto_tag: true
    build_args:
      - DOCKER_IMAGE_VERSION=${DRONE_TAG}
    tags:
      - "latest"

trigger:
  target:
  - production


---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- development
- production

trigger:
  status:
  - success
  - failure
