pipeline:
    publish:
        image: plugins/docker
        group: production
        repo: joseluisq/rust-linux-darwin-builder
        dockerfile: ./docker/Dockerfile
        username:
            from_secret: dockerhub_username
        password:
            from_secret: dockerhub_password
        auto_tag: true
        build_args:
            - DOCKER_IMAGE_VERSION=${DRONE_TAG}
        when:
            event: tag
        branch: master

    notification:
        image: plugins/slack
        webhook:
            from_secret: slack_webhook
        channel: ci-cd
        when:
            status: [success, failure]
